name: Deploy to EC2

on:
  push:
    branches:
      - feature/7-gh-actions-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-quart-app .

    - name: Push Docker image to registry
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_TOKEN
        docker push quart_example
