name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-quart-app .

    - name: Push Docker image to registry
      env:
        DOCKER_HUB_USERNAME: ${{ development-scratch.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ development-scratch.DOCKER_HUB_PASSWORD }}
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker push quart_example
