name: Deploy to EC2

on:
  push:
    branches:
      - feature/9-additional-pytest-coverage-job

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version=1.8.2

      - name: Configure Poetry
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install

      - name: Install coverage.py
        run: |
          poetry add coverage --group=dev

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage lcov

      - name: Check coverage percentage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: ./coverage.lcov
          min_coverage: 80
          exclude: '**/__init__.py tests/**'
  
  build:
    needs: coverage
    environment: development-scratch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build --no-cache -t ryandavis7/quart_example:latest .
      
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push Docker image to registry
        run: |
          docker push ryandavis7/quart_example:latest

  deploy:
    needs: build
    environment: development-scratch
    runs-on: ubuntu-latest
    steps:
      - name: SSH into AWS EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP_ADDRESS }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          password: ${{ secrets.AWS_EC2_PASSWORD }}
          script: |
            # Pull Docker image from registry
            echo "${{ secrets.AWS_EC2_PASSWORD }}" | sudo -S docker pull ryandavis7/quart_example:latest
            echo "hello world!"
            
            # Run Docker container
            echo "${{ secrets.AWS_EC2_PASSWORD }}" | sudo -S docker run -d -p 80:80 ryandavis7/quart_example:latest
            echo "${{ secrets.AWS_EC2_PASSWORD }}" | sudo -S docker ps
